-- begin TEST5POKEMON_POKEMON
alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_TRAINER foreign key (TRAINER_ID) references TEST5POKEMON_TRAINER(ID)^
alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_POKEMON foreign key (POKEMON_ID) references TEST5POKEMON_POKEMON_1(ID)^
create index IDX_TEST5POKEMON_POKEMON_ON_TRAINER on TEST5POKEMON_POKEMON (TRAINER_ID)^
create index IDX_TEST5POKEMON_POKEMON_ON_POKEMON on TEST5POKEMON_POKEMON (POKEMON_ID)^
-- end TEST5POKEMON_POKEMON
-- begin TEST5POKEMON_POKEMON_1
alter table TEST5POKEMON_POKEMON_1 add constraint FK_TEST5POKEMON_POKEMON_1_ON_TYPE foreign key (TYPE_ID) references TEST5POKEMON_TYPE(ID)^
create index IDX_TEST5POKEMON_POKEMON_1_ON_TYPE on TEST5POKEMON_POKEMON_1 (TYPE_ID)^
-- end TEST5POKEMON_POKEMON_1
