-- begin TEST5POKEMON_TRAINER
alter table TEST5POKEMON_TRAINER add constraint FK_TEST5POKEMON_TRAINER_ON_POKEMON foreign key (POKEMON_ID) references TEST5POKEMON_POKEMON(ID)^
create index IDX_TEST5POKEMON_TRAINER_ON_POKEMON on TEST5POKEMON_TRAINER (POKEMON_ID)^
-- end TEST5POKEMON_TRAINER
-- begin TEST5POKEMON_POKEMON
alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_TYPE foreign key (TYPE_ID) references TEST5POKEMON_TYPE(ID)^
create index IDX_TEST5POKEMON_POKEMON_ON_TYPE on TEST5POKEMON_POKEMON (TYPE_ID)^
-- end TEST5POKEMON_POKEMON
