-- begin TEST5POKEMON_POKEMON
alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_TYPE foreign key (TYPE_ID) references TEST5POKEMON_TYPE(ID)^
alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_TRAINER foreign key (TRAINER_ID) references TEST5POKEMON_TRAINER(ID)^
create index IDX_TEST5POKEMON_POKEMON_ON_TYPE on TEST5POKEMON_POKEMON (TYPE_ID)^
create index IDX_TEST5POKEMON_POKEMON_ON_TRAINER on TEST5POKEMON_POKEMON (TRAINER_ID)^
-- end TEST5POKEMON_POKEMON
