alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_POKEMON foreign key (POKEMON_ID) references TEST5POKEMON_POKEMON_1(ID);
create index IDX_TEST5POKEMON_POKEMON_ON_POKEMON on TEST5POKEMON_POKEMON (POKEMON_ID);
