alter table TEST5POKEMON_POKEMON add constraint FK_TEST5POKEMON_POKEMON_ON_TRAINER foreign key (TRAINER_ID) references TEST5POKEMON_TRAINER(ID);
create index IDX_TEST5POKEMON_POKEMON_ON_TRAINER on TEST5POKEMON_POKEMON (TRAINER_ID);
