alter table TEST5POKEMON_TRAINER alter column POKEMON_ID rename to POKEMON_ID__U01770 ^
alter table TEST5POKEMON_TRAINER alter column POKEMON_ID__U01770 set null ;
drop index IDX_TEST5POKEMON_TRAINER_ON_POKEMON ;
alter table TEST5POKEMON_TRAINER drop constraint FK_TEST5POKEMON_TRAINER_ON_POKEMON ;
