alter table TEST5POKEMON_POKEMON_1 add constraint FK_TEST5POKEMON_POKEMON_1_ON_TYPE foreign key (TYPE_ID) references TEST5POKEMON_TYPE(ID);
create index IDX_TEST5POKEMON_POKEMON_1_ON_TYPE on TEST5POKEMON_POKEMON_1 (TYPE_ID);
